# STAT 207 Group Lab Assignment 7 - [10 total points]

## Confidence Intervals

<hr>

## <u>Lab Grading</u>:

Should we grade your submission?  If not, write the netID of the submission to be graded.  (Note: We will only grade one assignment per group, and we'll pick the first one that says we should grade that submission.  We will assign the same grade to all team members.)

*For example*, you might respond: **grade this submission** or **my submission is under netID jdeeke**

If you said **my submission is under netID** above, we will not read any more of your lab submission.

If you said **grade this submission** above, who worked with you on this submission?  Write both their **names** and **netIDs**.  

Also, discuss and record whether each of you have seen a meteor shower or a "shooting star" before.  There is a meteor shower above Illinois through Thursday.

<hr>

## <u>Purpose</u>:
You should work in groups of 2-3 on this report (not working in groups without permission will result in a point deduction). The purpose of this group lab assignment is to generate two confidence intervals.
<hr>

## <u>Assignment Instructions</u>:

### Group Roles

Suggested and specified roles are provided below: 

#### Groups of 2

* **Driver**: This student will type the report.  While typing the report, you may be the one who is selecting the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  Specific ways to help may include: outlining the general steps needed to solve a question (providing the overview), locating examples within the course notes, and reviewing each line of code as it is typed.

#### Groups of 3

* **Driver**: This student will type the report.  They may also be the one to select the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  They may select the general approach to answering the question and/or a few steps to be completed along the way. 
* **Communicator**: This student will review the report (as it is typed) to ensure that it is clear and concise.  This student may also locate relevant examples within the course notes that may help complete the assignment.

<hr>

### Imports

In [36]:
#Run this
import pandas as pd                    # imports pandas and calls the imported version 'pd'
import matplotlib.pyplot as plt        # imports the package and calls it 'plt'
import seaborn as sns                  # imports the seaborn package with the imported name 'sns'
sns.set()

## Case Study: Near Earth Objects

We'd like to learn more about **all** objects that pass by the earth closely, in the past or in the future.  NASA has a database on near-Earth objects (NEOs) available from their website: https://cneos.jpl.nasa.gov/ca/.  We have prepared and provided for you this dataset for objects within the past year with a passing distance of less than 0.1 au.  The data was downloaded on October 6, 2024.

Variables in the data include:

- **CA DistanceNominal (au)**: the most likely distance between the object and Earth (measured between the center of each object, measured in astronomical units)
- **CA DistanceMinimum (au)**: the minimum possible distance between the object and Earth (measured between the center of the object, measured in astronomical units)
- **V relative(km/s)**: object velocity relative to Earth during its close-approach
- **V infinity(km/s)**: object velocity relative to a massless Earth during its close-approach
- **H(mag)**: asteroid absolute magnitude (smaller H implies larger asteroid diameter)
- **Rarity**: how infrequent a close approach is for asteroids of the same size or larger (larger values are less frequent)

Based on the data, you will pick an appropriate variable and question of interest that you will answer using a confidence interval.

## 1. [1 point] Prepare the Data

For this question, you will pick one of the first 5 variables, select a parameter to learn about, and then clean your data.

**a)** Which of the first 5 variables are you interested in learning about?

We want to look at the **V relative(km/s** variable

**b)** What parameter are you interested in estimating for the variable selected in part **a**?  You will work with this parameter in Question 2.

Define your parameter of interest for a single population (both with a symbol if possible and in writing).

Population mean relative velocity (μ)

**c)** Read in your data.  There should not be any missing values present in your data.

In [37]:
df = pd.read_csv('NEO Earth Close Approaches.csv')
df

,Object,Close-Approach (CA) Date,CA DistanceNominal (au),CA DistanceMinimum (au),V relative(km/s),V infinity(km/s),H(mag),Diameter,Rarity
0,415029 (2011 UL21),2024-Jun-27 20:16 ± < 00:01,0.04439,0.04439,25.88,25.88,15.9,1.7 km - 3.9 km,3
1,(2024 MK),2024-Jun-29 13:49 ± < 00:01,0.00197,0.00197,9.37,9.22,22.0,100 m - 230 m,3
2,(2024 ON),2024-Sep-17 10:19 ± < 00:01,0.00668,0.00668,8.88,8.83,20.4,220 m - 500 m,3
3,(2011 GA),2023-Oct-15 07:09 ± < 00:01,0.01743,0.01743,16.59,16.59,20.7,190 m - 420 m,2
4,(1998 HH49),2023-Oct-17 00:33 ± < 00:01,0.00784,0.00784,14.79,14.76,21.4,140 m - 310 m,2
...,...,...,...,...,...,...,...,...,...
2296,(2024 TL2),2024-Oct-06 09:12 ± < 00:01,0.00071,0.00070,9.12,8.70,30.7,1.9 m - 4.2 m,0
2297,(2018 RY1),2024-Oct-06 12:11 ± < 00:01,0.05488,0.05488,6.69,6.68,24.4,34 m - 77 m,0
2298,(2024 SD6),2024-Oct-06 16:39 ± < 00:01,0.01236,0.01231,6.78,6.75,27.5,8.2 m - 18 m,0
2299,(2022 FC5),2024-Oct-06 20:22 ± < 00:01,0.04152,0.04151,19.32,19.31,24.8,29 m - 66 m,0
2300,(2022 TD),2024-Oct-06 21:48 ± < 00:01,0.05937,0.05937,8.41,8.41,27.7,7.6 m - 17 m,0

**d)** Create a `Rare` variable that records a value of 1 or True if the object is rare (has a `Rarity` value of 1 or more) and a value of 0 or False if the object is not particularly rare (has a `Rarity` value of 0).

In [38]:
df['Rare'] = df['Rarity'] >= 1
df

,Object,Close-Approach (CA) Date,CA DistanceNominal (au),CA DistanceMinimum (au),V relative(km/s),V infinity(km/s),H(mag),Diameter,Rarity,Rare
0,415029 (2011 UL21),2024-Jun-27 20:16 ± < 00:01,0.04439,0.04439,25.88,25.88,15.9,1.7 km - 3.9 km,3,True
1,(2024 MK),2024-Jun-29 13:49 ± < 00:01,0.00197,0.00197,9.37,9.22,22.0,100 m - 230 m,3,True
2,(2024 ON),2024-Sep-17 10:19 ± < 00:01,0.00668,0.00668,8.88,8.83,20.4,220 m - 500 m,3,True
3,(2011 GA),2023-Oct-15 07:09 ± < 00:01,0.01743,0.01743,16.59,16.59,20.7,190 m - 420 m,2,True
4,(1998 HH49),2023-Oct-17 00:33 ± < 00:01,0.00784,0.00784,14.79,14.76,21.4,140 m - 310 m,2,True
...,...,...,...,...,...,...,...,...,...,...
2296,(2024 TL2),2024-Oct-06 09:12 ± < 00:01,0.00071,0.00070,9.12,8.70,30.7,1.9 m - 4.2 m,0,False
2297,(2018 RY1),2024-Oct-06 12:11 ± < 00:01,0.05488,0.05488,6.69,6.68,24.4,34 m - 77 m,0,False
2298,(2024 SD6),2024-Oct-06 16:39 ± < 00:01,0.01236,0.01231,6.78,6.75,27.5,8.2 m - 18 m,0,False
2299,(2022 FC5),2024-Oct-06 20:22 ± < 00:01,0.04152,0.04151,19.32,19.31,24.8,29 m - 66 m,0,False
2300,(2022 TD),2024-Oct-06 21:48 ± < 00:01,0.05937,0.05937,8.41,8.41,27.7,7.6 m - 17 m,0,False

## 2. [5 points] Single Population Confidence Interval

**a)** Provide your best estimate for the population parameter based on our available data.

In [39]:
df['V relative(km/s)'].mean()

10.702620599739243

**b)** Generate a sampling distribution using your available data as a stand-in for the population.

In [40]:
lst = []
for i in range(1000):
    sample = df.sample(1000)
    m = sample['V relative(km/s)'].mean()
    lst.append(m)
df2 = pd.DataFrame({'Mean V relative(km/s)':lst})
df2

     Mean V relative(km/s)
0                 10.82519
1                 10.58679
2                 10.55382
3                 10.51903
4                 10.57157
..                     ...
995               10.87197
996               11.11347
997               10.67258
998               10.52883
999               10.77446

[1000 rows x 1 columns]

**c)** Calculate a 90% confidence interval from your sampling distribution above.

In [41]:
print(df2.quantile(0.05))
print(df2.quantile(0.95))

Mean V relative(km/s)    10.497934
Name: 0.05, dtype: float64
Mean V relative(km/s)    10.919534
Name: 0.95, dtype: float64

**d)** Provide an interpretation of your final confidence interval.

The range of reasonable means for the V relative(km/s) variable is between 10.502419 km/s and 10.898772 km/s.

**e)** Provide an interpretation of the confidence level.

We are 90% sure that the true mean value for the V relative(km/s) variable is between 10.502419 km/s and 10.898772 km/s.

## 3. [4 points] Two Populations Confidence Interval

We'll now turn to a different parameter of interest that allows us to examine the difference between rare and regular NEOs.  For this parameter of interest, we'll use the difference between the parameter defined in **1b** between those objects that are rare compared to those that are more common.  This will allow us to understand how much larger the value is for rare objects than common ones.

**a)** First, provide your best estimate for the parameter(s) of interest using the available data.

In [48]:
test = df[['V relative(km/s)', 'Rare']].groupby(['Rare']).mean()
print(test)
print(14.101206 - 10.380871)

       V relative(km/s)
Rare
False         10.380871
True          14.101206
3.7203349999999986

**b)** Generate a sampling distribution for your parameter of interest.  

To do so, you should first separate your data into a Rare data frame and a Common data frame.  For each repetition inside a `for` loop, you'll take a sample from each of your two sets of data.  You will calculate the statistic from each re-sampled set of data.  Then, subtracting the two statistics allows you to capture your overall statistic of interest.  This re-sampled statistic is what you should save from each of your iterations.

In [43]:
df_Common = df[df['Rare'] == 0]
df_Rare = df[df['Rare'] >= 1]

print(df_Common.shape)
print(df_Rare.shape)

(2102, 10)
(199, 10)

In [44]:
raritylst = []
for i in range (1000):
    r_sample = df_Rare['V relative(km/s)'].sample(100, replace=True).mean()
    c_sample = df_Common['V relative(km/s)'].sample(100, replace=True).mean()
    raritylst.append(abs(r_sample - c_sample))
df_rarity = pd.DataFrame({'m': raritylst})
df_rarity

          m
0    3.6075
1    2.7751
2    3.7713
3    3.4097
4    4.5819
..      ...
995  3.9342
996  4.8187
997  2.7763
998  3.0445
999  4.5055

[1000 rows x 1 columns]

**c)** Pick a confidence level other than 90%.  Then, generate the corresponding confidence interval for our parameter of interest.

In [46]:
print(df_rarity.quantile(0.025))
print(df_rarity.quantile(0.975))

m    2.246705
Name: 0.025, dtype: float64
m    5.315642
Name: 0.975, dtype: float64

**d)** Does it seem plausible that there is no difference between the rare and common NEOs for your parameter of interest (corresponding to a value of 0 for your parameter of interest)?  Briefly explain.

Doesn't seem plausible because 0 is not in the interval